### ISSUE TITLE
Los constructores de la subclase deben llamar al constructor de la clase Carta con los parámetros necesarios (9 décimas)

### ISSUE THREAD

**Issue by gfhuertac** [dopazo/prueba0_lyp#2]
La clase carta ya define un constructor con la asignación de datos. Deben ocupar ese constructor pasando los datos necesarios (lo llamas vacío en algunos casos) y no asignar datos manualmente

**Comment by gfhuertac** [comment]
Dos cosas. 
1. Cuando arregles el issue debes agregar un comentario que diga donde lo arreglaste (eso típicamente se hace colocando un link al commit).
2. Igual no llamas al constructor que está en Carta

**Comment by dopazo** [comment]
Arreglado en commit 635d3653d073d3691ac4809ad9a6704290efd10f
Tengo un par de dudas, no entiendo por que me compila al hacer un super de esta forma y no se puede de la forma que está comentada

`super(Pinta.TREBOL, numero);`
`//super.pinta = Pinta.TREBOL;`
`//super.numero = numero;`

Y lo otro, si resolví todos lo issues en un commit, debo comentar todos? o puedo comentar solo este y decir que resolví los 3 de una?

**Comment by gfhuertac** [comment]
Las variables son de la instancia, por lo que si haces this.pinta o this.numero si funciona, pero no con super ya que no hay una instancia de super creada :)
